### ISSUE TITLE
Error while calculating offline progress

### ISSUE THREAD

**Issue by james-tindal** [kpwn243/melvor-quick-equip-manager#1]
It says "Cannot read property 'thieving' of undefined".
I was idling thieving at the time. The same message has since come up ("Cannot read property 'thieving') while I was offline, but not thieving.

<details><summary>Error message</summary>

```
An error occured while processing ticks offline:

Error due to the following mods:
Quick Equip Manager (v1.2.3)

Error Name: TypeError
Error Message: Cannot read property 'thieving' of undefined
Stack Trace:
TypeError: Cannot read property 'thieving' of undefined
    at Quick Equip Manager:setup.mjs:1:12247
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?6153:38:44)
    at Minibar.<anonymous> (Quick Equip Manager:setup.mjs:1:11810)
    at Minibar.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:840:52)
    at Bank.addItem (https://steam.melvoridle.com/assets/js/built/bank2.js?6153:96:19)
    at Bank.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:838:28)
    at https://steam.melvoridle.com/assets/js/built/skill.js?6153:350:113
    at Map.forEach (<anonymous>)
    at Rewards.giveRewards (https://steam.melvoridle.com/assets/js/built/skill.js?6153:350:54)

Active Action: melvorD:Thieving
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorF:Potion_Makers_Body
Platelegs: melvorF:Potion_Makers_Leggings
Weapon: melvorF:Staff_of_Earth
Amulet: melvorD:Clue_Chasers_Insignia
Ring: melvorD:Ancient_Ring_Of_Mastery
Gloves: melvorF:Thieving_Gloves
Cape: melvorTotH:Superior_Firemaking_Skillcape
Summon1: melvorF:Summoning_Familiar_Leprechaun
Consumable: melvorF:Herblore_Scroll_Of_XP

Action Information:
getErrorLog(){return `Is Active: ${this.isActive}\n`;}
  Selected Area: melvorF:GOLBIN_VILLAGE
  Selected NPC: melvorF:GOLBIN_CHIEF
  Stun State: 0
Modding Enabled. Loaded mods:
SEMI Core
Item Uses
Quick Item/Bank Wiki
Show Locked Astrology Modifiers
Action Workflows
Will I Die?
SEMI Save on Close
Completion Log Icons
Mastery Pool Can Overflow
Shining Star
Handy Dandy Notebook
Priority Miner
I hate RNG
dev.Console
Shop Item Owned Indicator
Macroscripts
SEMI Auto Farming
ETA
Real Quick Equip
Right Click To Sell
Skilling Closet
Quick Equip Manager
Unlimited Offline
Better Offline Recap
SEMI Auto Sell
Better Summoning Menu
Auto Township Cape
Township Runes
Township Auto Repair
Upgrade All Potions
Show Slayer Task Attack Style
```
</details>

**Comment by james-tindal** [comment]
Also this happened when I made a seed pouch:

```
An error occurred while processing ticks:

Error due to the following mods:
Quick Equip Manager (v1.2.3)

Error Name: Error
Error Message: Unknown slot translation Consumable
Stack Trace:
Error: Unknown slot translation Consumable
    at Quick Equip Manager:setup.mjs:1:12184
    at Quick Equip Manager:setup.mjs:1:12228
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?6153:38:44)
    at Minibar.<anonymous> (Quick Equip Manager:setup.mjs:1:11810)
    at Minibar.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:840:52)
    at Bank.addItem (https://steam.melvoridle.com/assets/js/built/bank2.js?6153:96:19)
    at Bank.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:838:28)
    at https://steam.melvoridle.com/assets/js/built/skill.js?6153:350:113
    at Map.forEach (<anonymous>)

Active Action: melvorD:Crafting
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorF:Crafters_Body
Platelegs: melvorF:Crafters_Leggings
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorF:Staff_of_Earth
Amulet: melvorD:Clue_Chasers_Insignia
Ring: melvorD:Ancient_Ring_Of_Mastery
Gloves: melvorF:Thieving_Gloves
Cape: melvorTotH:Superior_Firemaking_Skillcape
Summon1: melvorF:Summoning_Familiar_Monkey
Summon2: melvorF:Summoning_Familiar_Octopus
Consumable: melvorF:Gem_Preserver_Scroll

Action Information:
Is Active: true

Selected Recipe ID: melvorF:Runecrafting_Pouch
Modding Enabled. Loaded mods:
SEMI Core
Item Uses
Quick Item/Bank Wiki
Show Locked Astrology Modifiers
Action Workflows
Will I Die?
SEMI Save on Close
Completion Log Icons
Mastery Pool Can Overflow
Shining Star
Handy Dandy Notebook
Priority Miner
I hate RNG
dev.Console
Shop Item Owned Indicator
Macroscripts
SEMI Auto Farming
ETA
Real Quick Equip
Right Click To Sell
Skilling Closet
Quick Equip Manager
Unlimited Offline
Better Offline Recap
SEMI Auto Sell
Better Summoning Menu
Auto Township Cape
Township Runes
Township Auto Repair
Upgrade All Potions
Show Slayer Task Attack Style
Time Skip
Bank Tab Icons
Show Skill Modifiers
```

**Comment by kpwn243** [comment]
This issue has been fixed
