### ISSUE TITLE
Unknown slot translation consumable

### ISSUE THREAD

**Issue by james-tindal** [kpwn243/melvor-quick-equip-manager#2]
This happened when I made a Runecrafting Pouch.
The same thing also happened when I made a Seed Pouch, and when I made a Thief's Moneysack.
But only the first time. Never happened for the Alchemist's Bag.

<details><summary>Error message</summary>

```
An error occurred while processing ticks:

Error due to the following mods:
Quick Equip Manager (v1.2.3)

Error Name: Error
Error Message: Unknown slot translation Consumable
Stack Trace:
Error: Unknown slot translation Consumable
    at Quick Equip Manager:setup.mjs:1:12184
    at Quick Equip Manager:setup.mjs:1:12228
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (https://steam.melvoridle.com/assets/js/built/namespaceRegistry.js?6153:38:44)
    at Minibar.<anonymous> (Quick Equip Manager:setup.mjs:1:11810)
    at Minibar.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:840:52)
    at Bank.addItem (https://steam.melvoridle.com/assets/js/built/bank2.js?6153:96:19)
    at Bank.typeName.<computed> (https://steam.melvoridle.com/assets/js/built/mod.js?6153:838:28)
    at https://steam.melvoridle.com/assets/js/built/skill.js?6153:350:113
    at Map.forEach (<anonymous>)

Active Action: melvorD:Crafting
Current Equipment:
Helmet: melvorD:Crown_of_Rhaelyx
Platebody: melvorF:Crafters_Body
Platelegs: melvorF:Crafters_Leggings
Boots: melvorF:Boots_Of_Stealth
Weapon: melvorF:Staff_of_Earth
Amulet: melvorD:Clue_Chasers_Insignia
Ring: melvorD:Ancient_Ring_Of_Mastery
Gloves: melvorF:Thieving_Gloves
Cape: melvorTotH:Superior_Firemaking_Skillcape
Summon1: melvorF:Summoning_Familiar_Monkey
Summon2: melvorF:Summoning_Familiar_Octopus
Consumable: melvorF:Gem_Preserver_Scroll

Action Information:
Is Active: true

Selected Recipe ID: melvorF:Runecrafting_Pouch
Modding Enabled. Loaded mods:
SEMI Core
Item Uses
Quick Item/Bank Wiki
Show Locked Astrology Modifiers
Action Workflows
Will I Die?
SEMI Save on Close
Completion Log Icons
Mastery Pool Can Overflow
Shining Star
Handy Dandy Notebook
Priority Miner
I hate RNG
dev.Console
Shop Item Owned Indicator
Macroscripts
SEMI Auto Farming
ETA
Real Quick Equip
Right Click To Sell
Skilling Closet
Quick Equip Manager
Unlimited Offline
Better Offline Recap
SEMI Auto Sell
Better Summoning Menu
Auto Township Cape
Township Runes
Township Auto Repair
Upgrade All Potions
Show Slayer Task Attack Style
Time Skip
Bank Tab Icons
Show Skill Modifiers
```
</details>

**Comment by kpwn243** [comment]
This issue has been fixed
